/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jgoogleadsense;

import com.robtheis.aptr.language.Language;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author lauren
 */
public class JLoginPanel extends javax.swing.JFrame
{
    MyClass c = new MyClass();
    
    /**
     * Creates new form JLoginPanel
     */
    public JLoginPanel()
    {
        initComponents();
        
        this.txtUsuario.setText("");
        this.txtClave.requestFocus();
        
        //c.Listar_Archivos(c.Obtener_Directorio_Actual() + "/src/jgoogleadsense/Contenido/xPagina/Nombres/Niñas", 1);
        
        //c.Listar_Archivos(c.Obtener_Directorio_Actual() + "/src/jgoogleadsense/Contenido/xPagina/Nombres/Niños", 2);
        
        JCancioneroFlautaDulce flauta = new JCancioneroFlautaDulce();
        
        // this.pruebas();
    }
        
    public void prueba()
    {
        //c.ObtenerContenidoSOF("how-to-access-specific-element-of-dictionary-of-tuples.html", "how-to-access-specific-element-of-dictionary-of-tuples.html", "how-to-access-specific-element-of-dictionary-of-tuples", "how to access specific element of dictionary of tuples");
        
        //c.ObtenerListadoSOF();
        
        //c.EjecutarProcedimiento("SELECT * FROM sp_ingresar_enlace('prueba1', 'prueba2');");
        //System.out.println(JApertiumTranslator.Traducir("La casa es verde", Language.SPANISH, Language.ENGLISH));
        
        //c.EstablecerCorreoBlog("prueba@google");
        
        //c.Listar_Archivos("/home/lauren/Vídeos/", 1);
        
        //String texto = c.LeerArchivo(c.Obtener_Directorio_Actual() + "/src/jgoogleadsense/Contenido/xDocumento/Cancionero_Flauta_ dulce.doc");
        
        //System.out.println(texto);
        
        //System.out.println(c.Obtener_Directorio_Actual());
        
        //c.ConectarSQLLite();
        //c.LeerInfoSQLite("SELECT * FROM enlace e;");
        //c.EjecutarSentenciaSQLite("insert into enlace values(1, 'http://www.stackoverflow.com', 'stackoverflow', '130715', 'SPANISH', 'S');");
        
        //c.IngresarEnlace("http://www.stackoverflow.com", "stackoverflow", "SPANISH", "S");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClave = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnSalir = new javax.swing.JButton();
        btnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lblClave.setText("Clave:");
        getContentPane().add(lblClave);
        lblClave.setBounds(20, 57, 70, 20);

        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(20, 20, 70, 17);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(90, 10, 210, 27);
        getContentPane().add(txtClave);
        txtClave.setBounds(90, 50, 210, 27);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(200, 90, 100, 29);

        btnConectar.setText("Conectar");
        btnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConectar);
        btnConectar.setBounds(90, 90, 100, 29);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-352)/2, (screenSize.height-166)/2, 352, 166);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarActionPerformed
       // TODO add your handling code here:
       c.VerificarConexionCorreo(this.txtUsuario.getText() + "@gmail.com", this.txtClave.getText());
       setVisible(false);
       JPrincipal principal = new JPrincipal();
    }//GEN-LAST:event_btnConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JLoginPanel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
